[tool.poetry]
name = "jabberjaw"
version = "0.1.0"
description = ""
authors = ["imry <imry.rosnebaum@droitfintech.com>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.19.5"
pandas = "^1.2.0"
pandas-datareader = "^0.9.0"
matplotlib = "^3.3.3"
pyaml = "^20.4.0"
tables = "^3.6.1"
bs4 = "^0.0.1"
dpath = "^2.0.1"



[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
