[tool.poetry]
name = "jabberjaw"
version = "0.1.0"
description = ""
authors = ["imry <imry.rosnebaum@droitfintech.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.0.4"
numpy = "^1.18.5"
pyyaml = "^5.3.1"
pyarrow = "^0.17.1"
yfinance = "^0.1.54"
Quandl = "^3.5.0"
xlrd = "^1.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
